### ISSUE TITLE
Create POST for check an uncheck for App Mobile

### ISSUE THREAD

**Issue by mamartinez** [kylephillips/favorites#46] opened 2016-03-04 16:31 UTC
I created a question on Stackoverflow

http://stackoverflow.com/questions/35796311/create-post-protocol-for-wordpress-from-reading-debugging-tool-chrome

Thank You

**Comment by kylephillips** [comment] 2017-06-10 14:03
Duplicate of #47

**Closed by kylephillips** 2017-06-10 14:03 UTC
