### ISSUE TITLE
Cannot read property 'posts' of undefined

### ISSUE THREAD

**Issue by wpsoul** [kylephillips/favorites#51] opened 2016-04-27 10:09 UTC
I have a bug with plugin.

Here line of code which makes issue http://screencast.com/t/5Qj2K3zQn

http://screencast.com/t/R4pdtC57

**Comment by kylephillips** [comment] 2017-06-10 14:06
I'm closing, as I'm unable to reproduce this issue

**Closed by kylephillips** 2017-06-10 14:06 UTC

**Comment by poncianodiego** [comment] 2017-07-18 22:14
I am experiencing this issue as well
